name: Java CI test with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    
    # Adding the creationg of a JAR artifact. The artifact will be available in the summary page of the workflow result
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-jar
        path: build/libs/*.jar
    
    # Step to check if the java file built exists
    - name: List generated JARs
      run: ls -l build/libs

    # Pushing the building result as Docker image in DockerHub - commands or action?  
    - name: Build and push Docker image
      # Action take from: https://github.com/marketplace/actions/docker-build-push-action
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: mmartinelli91/gh-actions-app
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}